# =============================
# config.py
# Cấu hình chung cho Jetson / laptop
# =============================

# Camera
OPENNI_PATH_WINDOWS = r"C:\Program Files\OpenNI_v2.3.0.86\Win64-Release\sdk\libs"
OPENNI_PATH_LINUX = "/home/huyjetson/mobile_robot/ai/Orbbec_OpenNI_v2.3.0.86-beta6_linux_release/OpenNI_2.3.0.86_202210111155_4c8f5aa4_beta6_a311d_arm64/OpenNI_2.3.0.86_202210111155_4c8f5aa4_beta6_a311d/sdk/libs"

COLOR_W = 640
COLOR_H = 480
DEPTH_W = 640
DEPTH_H = 480

CAM_W = 560
CAM_H = 400

ENABLE_FLIP = False
FLIP_CODE = 1

# Depth
MIN_DEPTH_MM = 300
MAX_DEPTH_MM = 5000
DEPTH_ALPHA = 0.25

DEPTH_ROI_X1_RATIO = 0.35
DEPTH_ROI_X2_RATIO = 0.65
DEPTH_ROI_Y1_RATIO = 0.30
DEPTH_ROI_Y2_RATIO = 0.70

# YOLO / tracking
MODEL_PATH = "models/yolo26n.engine"
POSE_MODEL_PATH = "models/yolo26n-pose.engine"

OWNER_ID = 1
PREPARE_COUNTDOWN = 5
ENROLL_FRAMES = 30
MAX_OWNER_SAMPLES = 12

MIN_BOX_W = 55
MIN_BOX_H = 110

SIM_THRESHOLD_REACQUIRE = 0.70
KEEP_TARGET_THRESHOLD = 0.52

REACQUIRE_CONFIRM_FRAMES = 2
TARGET_LOST_TOLERANCE = 2

TRACKING_REID_INTERVAL = 2
REACQUIRE_REID_INTERVAL = 1

MAX_REID_CANDIDATES_REACQUIRE = 10

CROP_W = 64
CROP_H = 128

EMB_WEIGHT = 0.84
MOTION_WEIGHT = 0.13
SHIRT_WEIGHT = 0.03

TRACK_ID_BONUS = 0.28

# Fall detection - YOLO Pose
POSE_CONF = 0.30
POSE_KPT_CONF = 0.25
POSE_IMGSZ = 192

POSE_RUN_INTERVAL = 3
MAX_POSE_PEOPLE = 2

FALL_BOX_MIN_W = 60
FALL_BOX_MIN_H = 45
FALL_BOX_MIN_AREA = 5000

# Fall detection - side fall
FALL_TORSO_MAX_DEG = 30.0
FALL_LOW_HIP_RATIO = 0.62
FALL_LOW_SHOULDER_RATIO = 0.48
FALL_BOX_ASPECT_MIN = 1.15

# Fall detection - motion
FALL_DROP_PX = 28.0
FALL_SHOULDER_DROP_PX = 30.0
FALL_HEIGHT_SHRINK_RATIO = 0.72
FALL_COMPACT_RATIO = 0.52
FALL_DEPTH_TILT_MM = 220.0

# Fall detection - forward/back fall
FORWARD_FALL_HIP_RATIO = 0.52
FORWARD_FALL_SHOULDER_RATIO = 0.35

FORWARD_MIN_STAND_FRAMES = 12
FORWARD_FAST_CENTER_DROP_RATIO = 0.055

FORWARD_BOX_HEIGHT_RATIO = 0.80 #độ nhạy khi té đột ngột
FORWARD_CENTER_DROP_RATIO = 0.090 #độ tụt tâm người
FORWARD_HIP_DROP_RATIO = 0.090
FORWARD_SHOULDER_DROP_RATIO = 0.090

FORWARD_COMPACT_RATIO = 0.68

FORWARD_NO_DEPTH_COMPACT_RATIO = 0.58
FORWARD_NO_DEPTH_HEIGHT_RATIO = 0.70

FORWARD_DEPTH_TILT_MM_SOFT = 150.0
FORWARD_DEPTH_HEIGHT_RATIO = 0.86
FORWARD_CENTER_DROP_RATIO_SOFT = 0.110

FORWARD_POSE_SCAN_EVERY = 2
FORWARD_BASELINE_ALPHA = 0.08

# Fall detection - confirm / clear
FALL_CONFIRM_FRAMES = 5
FALL_CLEAR_FRAMES = 6
FALL_ALERT_HOLD_SEC = 1.0

RECOVER_CONFIRM_FRAMES = 3
STATE_TRACK_TIMEOUT = 1.5

# Standing baseline
STAND_TORSO_MIN_DEG = 58.0
STAND_BOX_ASPECT_MAX = 0.95
STAND_HIP_RATIO_MAX = 0.64
STAND_SHOULDER_RATIO_MAX = 0.48

# Recover after fall
RECOVER_MIN_HEIGHT_RATIO = 0.50
RECOVER_TORSO_MIN_DEG = 55.0
RECOVER_HIP_RATIO_MAX = 0.64
RECOVER_BOX_ASPECT_MAX = 1.05

# Anti ID-switch
ID_SWITCH_CENTER_DIST_PX = 140.0
ID_SWITCH_HEIGHT_RATIO_MIN = 0.55
ID_SWITCH_HEIGHT_RATIO_MAX = 1.80

# Sit detection
SIT_TORSO_MIN_DEG = 40.0
SIT_LOW_HIP_RATIO = 0.42
SIT_MIN_HEIGHT_RATIO = 0.38
KNEE_MARGIN_PX = 8.0

# Bend detection
BEND_TORSO_MIN_DEG = 32.0
BEND_TORSO_MAX_DEG = 58.0
BEND_HIP_MAX_RATIO = 0.60

# Kneel detection
KNEEL_MIN_HEIGHT_RATIO = 0.45

SHOW_FPS = True